### ISSUE TITLE
Feature request: Add readline support

### ISSUE THREAD

**Issue by mewmew** [karlek/chell#2]
This would allow previous commands to be located using the arrow keys. E.g. press "up arrow" to get the last command.

You could also use `rlwrap` to achieve the same effect.

```
$ rlwrap chell
(^._.^)ﾉ @ /home/u/Desktop/chell $ ls
chell  chell.c  README.md
time: 0.003s
### Pressing "up arrow" ###
(^._.^)ﾉ @ /home/u/Desktop/chell $ ls
```

**Comment by karlek** [comment]
I'm thinking a circular linked list. Thereby making it easy to overwrite old entries and you can easily add things in constant time. However searching with a 'ctrl+r' feature would be in linear time (which might be implemented in the future).

**Comment by mewmew** [comment]
Readline does more than simply remembering command history. It also enabled "right arrow" and "left arrow" actions.

Pressing "left arrow" twice using chell currently results in:

```
top/chell $ ls^[[D^[[D
```

**Comment by mewmew** [comment]
> However searching with a 'ctrl+r' feature would be in linear time

This won't matter too much, as the command history will be < 10^4 and will more likely be limited by user interaction that computation time. E.g. the time it takes to enter letter on the keyboard.

**Comment by karlek** [comment]
Arrow keys use hardware specific ascii codes which makes this quite boring and tedious to implement. I'll just `alias chell='rlwrap chell'`.
