### ISSUE TITLE
Assignment 'foreground / background'

### ISSUE THREAD

**Issue by karlek** [karlek/chell#6]
It should handle the execution of processes in foreground and background. For foreground processes the total execution time for the process should be printed when it terminates. For background process information on that they have terminated should be printed no later than when the shell prompts next time after the background process/es have terminated.
- [x] Foreground
- [x] Background

**Comment by karlek** [comment]
@nejlika: I've got a hard time interpreting the last sentence about when the information about the background process should be printed. Any thoughts? Is it correct atm?

**Comment by nejlika** [comment]
Unique identifier for terminated background processes would be nice.
